version: '3.7'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pyplayground
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
